services:
  3x-ui:
    image: honeok/3x-ui
    restart: unless-stopped
    container_name: 3x-ui
    volumes:
      - $PWD/db/:/etc/x-ui
      - $PWD/cert/:/root/cert
    # environment:
    #   USER_NAME: admin
    #   USER_PASSWORD: admin
    #   BASE_PATH: admin
    #   PANEL_PORT: 54321
    network_mode: host