---
name: 'Build and Publish 3x-ui'

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: 'Build and Publish 3x-ui'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ github.repository_owner }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Fetch Versions and Determine Build'
        id: bump_version
        run: |
          XRAY_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/XTLS/Xray-core/releases | sed -n 's/.*"tag_name": *"v\([^"]*\)".*/\1/p' | sort -Vr | head -n1)"
          XUI_LTAG="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/MHSanaei/3x-ui/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
          XUI_LVER="${XUI_LTAG#v}"
          XUI_CVER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/honeok/3x-ui/tags 2>/dev/null | grep -o '"name": *"[^"]*"' | cut -d '"' -f 4 | grep -v "^latest$" | sort -Vr | head -n1 | cut -d'-' -f1 || true)"
          echo "xray_version=${XRAY_LVER}" >> "$GITHUB_OUTPUT"
          echo "xui_tag=${XUI_LTAG}" >> "$GITHUB_OUTPUT"
          echo "xui_version=${XUI_LVER}" >> "$GITHUB_OUTPUT"
          if [[ "$(printf '%s\n%s\n' "$XUI_LVER" "$XUI_CVER" | sort -V | head -n1)" != "$XUI_LVER" || (-z "$XUI_CVER" && -n "$XRAY_LVER" && -n "$XUI_LVER") ]]; then
            echo "IS_RENEW=1" >> "$GITHUB_ENV"
          fi

      - name: 'Set up Docker QEMU'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to DockerHub'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Extract Docker metadata'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/3x-ui
          tags: |
            type=raw,value=${{ steps.bump_version.outputs.xui_version }}
            type=raw,value=latest

      - name: 'Build and push 3x-ui image'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/core/3x-ui
          file: ${{ github.workspace }}/core/3x-ui/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            XRAY_VERSION=${{ steps.bump_version.outputs.xray_version }}
            XUI_TAG=${{ steps.bump_version.outputs.xui_tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true