name: CI

on:
  push:
    paths:
      - '*.sh'
      - '**/*.sh'
  pull_request:
    paths:
      - '*.sh'
      - '**/*.sh'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          if ! command -v shellcheck > /dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y shellcheck
          fi

      - name: Fetch all Git commits
        run: |
          git fetch --prune --unshallow

      - name: Lint changed .sh files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD | grep '\.sh$')

          # 没有.sh文件变化则跳过
          [ -z "$CHANGED_FILES" ] && exit 0

          # 对所有修改的.sh文件执行check
          for file in $CHANGED_FILES; do
            shellcheck "$file"
          done
