name: CI

on:
  push:
    paths:
      - '*.sh'
      - '**/*.sh'
  pull_request:
    paths:
      - '*.sh'
      - '**/*.sh'
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          # 安装shellcheck
          if ! command -v shellcheck > /dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y shellcheck
          fi

      - name: Get changed .sh files
        id: changes
        run: |
          CURRENT_COMMIT=$GITHUB_SHA
          
          # 获取前一个提交的哈希值，如果没有父提交则不进行对比
          PREVIOUS_COMMIT=$(git log --pretty=format:'%H' -n 2 | tail -n 1)
          
          # 如果没有找到前一个提交（即初次提交），直接处理当前提交
          if [ -z "$PREVIOUS_COMMIT" ]; then
            CHANGED_FILES=$(git diff --name-only $CURRENT_COMMIT | grep '\.sh$')
          else
            CHANGED_FILES=$(git diff --name-only $PREVIOUS_COMMIT $CURRENT_COMMIT -- | grep '\.sh$')
          fi
          
          [ -z "$CHANGED_FILES" ] && exit 0
          
          echo "$CHANGED_FILES" > changed_files.txt
          cat changed_files.txt

      - name: Lint changed .sh files
        run: |
          # 遍历所有修改过的.sh文件并进行check
          [ -f changed_files.txt ] && cat changed_files.txt | xargs -I {} shellcheck {}