---
name: 'Build and Publish v2ray'

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Publish v2ray'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Fetch Versions and Determine Build'
        run: |
          V2RAY_LTAG="$(wget -qO- --tries 5 "https://api.github.com/repos/v2fly/v2ray-core/releases" | sed -n 's/.*"tag_name": *"\(v[^"]*\)".*/\1/p' | sort -Vr | head -n1)"
          V2RAY_LVER="${V2RAY_LTAG#v}"
          V2RAY_CVER="$(wget -qO- --tries 5 "https://hub.docker.com/v2/repositories/honeok/v2ray/tags" 2>/dev/null | \
            jq -r ".results // [] | .[].name" | grep -v '^latest$' | sort -Vr | head -n1 | cut -d'-' -f1 || echo "")"
          if [[ -z "$V2RAY_LTAG" || -z "$V2RAY_LVER" ]]; then
            echo 'Error: Required parameters cannot be empty.'; exit 1
          fi
          echo "V2RAY_LTAG=$V2RAY_LTAG" >> $GITHUB_ENV
          echo "V2RAY_LVER=$V2RAY_LVER" >> $GITHUB_ENV
          echo "V2RAY_CVER=$V2RAY_CVER" >> $GITHUB_ENV
          if [[ "$(echo -e "$V2RAY_LVER\n$V2RAY_CVER" | sort -V | head -n1)" != "$V2RAY_LVER" || -z "$V2RAY_CVER" ]]; then
            echo "IS_RENEW=1" >> $GITHUB_ENV
          fi

      - name: 'Set up Docker QEMU'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to DockerHub'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Build and Push v2ray image'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.17.0
        with:
          context: "{{ defaultContext }}:core/v2ray"
          file: Dockerfile
          push: true
          tags: |
            "${{ env.DOCKER_USERNAME }}/v2ray:${{ env.V2RAY_LVER }}"
            "${{ env.DOCKER_USERNAME }}/v2ray:latest"
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
          build-args: VERSION=${{ env.V2RAY_LTAG }}