name: 'Build and publish x-ui '

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    name: 'Build and publish x-ui '
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Compare Xray-core and x-ui versions'
        run: |
          LATEST_VERSION=$(curl -fsSL "https://api.github.com/repos/XTLS/Xray-core/releases" | \
            jq -r 'map(select(.prerelease == true)) | sort_by(.created_at) | last | .tag_name' | sed 's/^v//') && \
          CURRENT_VERSION=$(bash -c 'set -o pipefail; curl -fsSL "https://hub.docker.com/v2/repositories/honeok/x-ui/tags" 2>/dev/null | \
            jq -r ".results // [] | .[].name" | grep -v "^latest$" | sort -Vr | head -n 1 | awk -F - "{print \$2}" || echo ""') && \
          if [ -z "$LATEST_VERSION" ]; then \
            echo "Error: Failed to obtain the latest version!" && exit 1; \
          fi && \
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
          if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]] || \
            [[ -z "$CURRENT_VERSION" ]]; then \
            echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"; \
          else \
            echo "BUILD_IMAGE=false" >> "$GITHUB_ENV"; \
          fi

      - name: 'Set up Docker QEMU'
        if: env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        if: env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Login to DockerHub'
        if: env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build and push x-ui image'
        if: env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.16.0
        with:
          context: "{{ defaultContext }}:fun/x-ui"
          file: Dockerfile
          push: true
          tags: |
            "${{ env.DOCKER_USERNAME }}/x-ui:xray-${{ env.LATEST_VERSION }}"
            "${{ env.DOCKER_USERNAME }}/x-ui:latest"
          platforms: linux/amd64, linux/arm64/v8, linux/s390x

      - name: 'Sync dockerhub README.md'
        if: env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch'
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/x-ui
          readme: "./fun/x-ui/README.zh_CN.md"