---
name: 'Build and Publish Xray'

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Publish Xray'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Fetch Versions and Determine Build'
        run: |
          XRAY_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/XTLS/Xray-core/releases | sed -n 's/.*"tag_name": *"v\([^"]*\)".*/\1/p' | sort -Vr | head -n1)"
          XRAY_CVER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/honeok/xray/tags 2>/dev/null | jq -r ".results // [] | .[].name" | grep -v "^latest$" | sort -Vr | head -n1 | cut -d'-' -f1 || echo "")"
          [ -z "$XRAY_LVER" ] && { echo "Error: Required parameters cannot be empty."; exit 1; }
          echo "XRAY_LVER=$XRAY_LVER" >> $GITHUB_ENV
          echo "XRAY_CVER=$XRAY_CVER" >> $GITHUB_ENV
          if [[ "$(echo -e "$XRAY_LVER\n$XRAY_CVER" | sort -V | head -n1)" != "$XRAY_LVER" || -z "$XRAY_CVER" ]]; then
            echo "IS_RENEW=1" >> "$GITHUB_ENV"
          fi

      - name: 'Set up Docker QEMU'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3.11.1

      - name: 'Login to DockerHub'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Build and push xray image'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ github.workspace }}/core/xray
          file: ${{ github.workspace }}/core/xray/Dockerfile
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
          build-args: XRAY_LVER=${{ env.XRAY_LVER }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/xray:${{ env.XRAY_LVER }}
            ${{ env.DOCKER_USERNAME }}/xray:latest
          push: true